name: Auto deploy master to production

on:
  push:
    branches: 
      - master

jobs:
  build_and_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.102
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]*"
    - name: Create deploy package for Systembolaget-Releases-Indexer
      run: |
         dotnet lambda package -pl src/Systembolaget.Releases.Indexer -c Release -o dist/Systembolaget.Releases.Indexer.zip        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/Systembolaget.API.functions/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/Systembolaget.API.functions/
    - name: Set up Node js
      uses: actions/setup-node@v1
      with:
        node-version: '12.6'
    - name: Build Web
      run: |
        npm install --prefix src/systembolaget.releases.web
        npm run build --prefix src/systembolaget.releases.web
    - name: Deploy Systembolaget-Releases-Indexer to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: Systembolaget-Releases-Indexer
        zip_file: dist/Systembolaget.Releases.Indexer.zip
    - name: Deploy Systembolaget-API-GetReleasesForDate to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: Systembolaget-API-GetReleasesForDate
        source: src/Systembolaget.API.functions/get-releases-for-date.py
    - name: Deploy Systembolaget-API-GetBeverageGroups to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: Systembolaget-API-GetBeverageGroups
        source: src/Systembolaget.API.functions/get-beverage-groups.py
    - name: Deploy Systembolaget-API-GetReleasesByGroup to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: Systembolaget-API-GetReleasesByGroup
        source: src/Systembolaget.API.functions/get-releases-by-group.py
