name: CI build for all branches

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.102
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]*"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/Systembolaget.API.functions/requirements.txt
    - name: Lint Python scripts
      run: |
        pip install flake8
        flake8 src/Systembolaget.API.functions/
        flake8 src/Systembolaget.Releases.Maintenance/
    - name: Set up Node js
      uses: actions/setup-node@v1
      with:
        node-version: '12.6'
    - name: Build Web
      run: |
        npm install --prefix src/systembolaget.releases.web
        npm run build --prefix src/systembolaget.releases.web
